### ISSUE TITLE
ValidationException when EventHubName length longer than 50

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-event-hubs-dotnet#162]
Nuget version 1.01

Steps to reproduce

1) Attempt to create an event hub with a name longer than 50 characters with Microsoft.Azure.

Microsoft.Rest.ValidationException: 'eventHubName' exceeds maximum length of '50'.
   at Microsoft.Azure.Management.EventHub.EventHubsOperations.<GetWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.EventHub.EventHubsOperationsExtensions.<GetAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

The legacy service bus library allows names longer than 50 characters.

**Comment by serkantkaraca** [comment]
This is not related to .NetCore client but related to management client, hence closing.
