### ISSUE TITLE
A large number of TimeoutException and ObjectDisposedException noticed during high load

### ISSUE THREAD

**Issue by NitishMittalHon** [Azure/azure-event-hubs-dotnet#248]
## Actual Behavior
1. A large number of TimeoutException and ObjectDisposedException noticed during high load
2. Following are the stack traces:
**TimeoutException:**
```
System.TimeoutException: Timed out trying to create FaultTolerantAmqpObject`1
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.EventHubClient.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**ObjectDisposedException:**
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FaultTolerantAmqpObject`1'.
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<CreateLinkAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.<OnCreateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Amqp.Singleton`1.<CreateValue>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventHubs.EventHubClient.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
We are seeing this issue happening randomly. We wants to understand what might be happening here. 
We are now handling these exceptions by closing the EvenHubClient and recreating it. We are not yet sure if it will fix the issue as it is transient.

## Versions  
- OS platform and version: Windows Server on Azure Cloud Service
- .NET Version: 4.5.1
- NuGet package version or commit ID: 1.0.3

**Comment by serkantkaraca** [comment]
Thanks for reporting the issue. Can you send me the following information while I am checking the code?

* How high is the load in terms of number of messages per second or minute?
* Typical message size?
* How many clients are running concurrently?
* How many throughput units is your namespace owning?
* Are you observing any client side resource saturation like high CPU, low memory, high number of threads etc?

**Comment by serkantkaraca** [comment]
Regarding ObjectDisposedException: I have checked the code. You are most probably closing the client while there are ongoing sends. We don't dispose the objects pointed in the exception stack other than during the close.

**Comment by NitishMittalHon** [comment]
Hi @serkantkaraca ,
Thanks for the reply. We checked the possibility of closing the eventhub client by a different thread. It looks the case here and is not related to load. Will refactor the code to manage the lifecycle of eventhub clients in  a better way to avoid this.

**Comment by serkantkaraca** [comment]
Closing the issue for now. Please reactivate if you find anything I can help.
