### ISSUE TITLE
When using a SASToken with expiry as one year from the time of generation, getting an exception saying "Time-out interval must be less than 2^32-2."

### ISSUE THREAD

**Issue by veeray90** [Azure/azure-event-hubs-dotnet#414]
## Actual Behavior
1. I generated an SASToken which expires after a year with the C# code snippet given at https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token. When using this SASToken that expires after 1 year with the EventProcessorHost, I am getting this exception 
"Time-out interval must be less than 2^32-2. Parameter name: dueTime" .  But if I generate the SASToken with a lesser expiry (ex: a week),  I am able to receive the events from the eventhub.

**Code used to generate SASToken:**
private static string createToken(string resourceUri, string keyName, string key)
{
    TimeSpan sinceEpoch = DateTime.UtcNow - new DateTime(1970, 1, 1);
    var week = 60 * 60 * 24 * 7;**(Used 365 here instead of 7)**
    var expiry = Convert.ToString((int)sinceEpoch.TotalSeconds + week);
    string stringToSign = HttpUtility.UrlEncode(resourceUri) + "\n" + expiry;
    HMACSHA256 hmac = new HMACSHA256(Encoding.UTF8.GetBytes(key));
    var signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(stringToSign)));
    var sasToken = String.Format(CultureInfo.InvariantCulture, "SharedAccessSignature sr={0}&sig={1}&se={2}&skn={3}", HttpUtility.UrlEncode(resourceUri), HttpUtility.UrlEncode(signature), expiry, keyName);
    return sasToken;
}

**StackTrace:** 
   at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
   at Microsoft.Azure.EventHubs.Amqp.ActiveClientLinkManager.ScheduleValidityTimer()
   at Microsoft.Azure.EventHubs.Amqp.ActiveClientLinkManager.SetActiveLink(ActiveClientLinkObject activeClientLink)
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<CreateLinkAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.<OnCreateAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.PartitionReceiver.<ReceiveAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<ReceivePumpAsync>d__18.MoveNext()

**Code used to register the eventhub:**
  private static async Task MainAsync(Action<object> funManageData)
        {
             EventHubsConnectionStringBuilder ehcon = new EventHubsConnectionStringBuilder(new Uri(<endpoint>), entityPath, sharedAccessSignature with1Yearexpiry, TimeSpan.FromMinutes(1));
           string consumerGroupName=<consumergroupname>;
            string entityPath=<eventhubentitypath>;
            string storageConnString = <storageconnectionstring>;
            string storageContainName= <containerName>;
          
            var item = new EventProcessorHost(
            entityPath,
            consumerGroupName,
            ehcon.ToString(),
            storageConString,
            StorageContainerName);

            try
                {
                // Registers the Event Processor Host and starts receiving messages
                var options = new EventProcessorOptions();
                options.ReceiveTimeout = TimeSpan.MinValue; 
                await item.RegisterEventProcessorFactoryAsync(new EventHubProcessorFactory(funManageData));
                }
                catch(Exception ex)
                {
                string message = ex.Message;
                }
            ServicePointManager.DefaultConnectionLimit = Int32.MaxValue;
          
            var builder = new HostBuilder();
            host = builder.Build();
            using (host)
            {
                await host.RunAsync();
            }
            // Disposes of the Event Processor Host
            await item.UnregisterEventProcessorAsync();  
        }

## Expected Behavior
If the SASToken is generated with an expiry date after a week, I am able to receive events. Why am I seeing the above exception if the expiry date is after a year?

## Versions  
- OS platform and version: Windows 10 Pro
- .NET Version: .NETStandard 2.0
- NuGet package version or commit ID: Micorost.Azure.EventHubs(4.1.0) Microsoft.Azure.EventHubs.Processor(4.1.0)

**Comment by serkantkaraca** [comment]
Thanks for reporting this. That sounds like a bug in the client, not directly related to processor host though. Let me build a repro and provide more details shortly.

**Comment by serkantkaraca** [comment]
Seems this bug is fixed as of 4.2.0 release. Please upgrade to up to date version.
