### ISSUE TITLE
GetPartitionRuntimeInformationAsync call returns null LastEnqueuedOffset intermittently.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs-dotnet#77]
Hit 2 null LastEnqueuedOffset returns from GetPartitionRuntimeInformationAsync calls during 12 hours stress run.

```
> <6760.19> 12/02/2016 12:48:12 - Error: NetCore-Management_0<stdout>:  <20> Exception caught (Identifier: Partition:1): System.Exception: Returned LastEnqueuedOffset is null
> <6760.19> 12/02/2016 12:48:12 - Error: NetCore-Management_0<stdout>:    at NetCoreStressClient.ManagementClient.<IssueGetPartitionRuntimeInfoCallAsync>d__11.MoveNext() in D:\DaylightEnlistments-EH\ServiceBus\Messaging\src\test\ServiceBus\Messaging\Testcases\Stress\EventHub\NetCoreScenarios\src\NetCoreStressClient\ManagementClient.cs:line 0
> <6760.23> 12/02/2016 12:48:13 - Info: NetCore-Receiver_0<stdout>:  <21> PendingSends:0 PendingReceives:4
> <6760.19> 12/02/2016 12:48:15 - Error: NetCore-Management_0<stdout>:  <41> Exception caught (Identifier: Partition:2): System.Exception: Returned LastEnqueuedOffset is null
> <6760.19> 12/02/2016 12:48:15 - Error: NetCore-Management_0<stdout>:    at NetCoreStressClient.ManagementClient.<IssueGetPartitionRuntimeInfoCallAsync>d__11.MoveNext() in D:\DaylightEnlistments-EH\ServiceBus\Messaging\src\test\ServiceBus\Messaging\Testcases\Stress\EventHub\NetCoreScenarios\src\NetCoreStressClient\ManagementClient.cs:line 0
```

**Comment by serkantkaraca** [comment]
This issue is identified as originated from service side and we will roll the fix out with our next service upgrade.
